### ISSUE TITLE
Append project name to archived items - broken?

### ISSUE THREAD

**Issue by pheraph** [irrationalistic/atom-tasks#39]
The following screenshot tells me that archived items get an @project(projectname) appended:

![Screenshot](https://raw.githubusercontent.com/irrationalistic/atom-tasks/master/images/tasks_example.png)

But my archived items are completely missing the project reference. Is this supposed to be working? Here's my config (I am using the taskpaper syntax):

```
  tasks:
    dateFormat: "DD.MM.YYYY HH:mm"
    completeMarker: "-"
    cancelledMarker: "-"
    baseMarker: "-"
```
