### ISSUE TITLE
Taskpaper and support for notes?

### ISSUE THREAD

**Issue by pheraph** [irrationalistic/atom-tasks#47]
I use the taskpaper-syntax for my tasks. According to the "TaskPaper’s File Format" (http://imissmymac.com/wp-content/uploads/2013/02/TaskPaper-Users-Guide.pdf) there are not only projects, tags and todos, but also notes:

> A note is any line that doesn't match the task or project rules.

It would be helpful if notes were colored in a more subtle tone. I helped myself with this little piece in my styles.less:

```less

atom-text-editor::shadow, atom-text-editor {

  .todo {
    // Notes
    color: @text-color-subtle;
  }

  .tasks {
    // Tasks
    &.text { color: @text-color-highlight; }
    // Projects
    &.header { color: @text-color-warning; }
  }

}
```

Although I'm totally fine with that solution I think it would be cool if the tasks-package supported it out of the box.
