### ISSUE TITLE
How do we have different formatting on tags

### ISSUE THREAD

**Issue by vastbinderj** [irrationalistic/atom-tasks#48]
I read a similar request to format the entire line, but all I care about is different colors for different tags.  In Plaintasks, I use red, orange, yellow and green for the states @critical, @high, @low, @today - respectively.

I tried adding the following style like you posted in another issue:

```
atom-text-editor::shadow, atom-text-editor {
  .source.todo {
    .attribute.urgent &{
      color: red;
    }
  }
}
```

However, they are still blue....

![image](https://cloud.githubusercontent.com/assets/713960/11251148/cb4b6b1a-8de4-11e5-8bb1-b2e049e3e03a.png)

**Comment by irrationalistic** [comment]
I don't think you need the extra `&` there. It should work if you do:
```less
atom-text-editor::shadow, atom-text-editor {
  .source.todo {
    .attribute.urgent {
      color: red;
    }
  }
}
```
